### ISSUE TITLE
Improving Querying Speeds

### ISSUE THREAD

**Issue by JJamesWWang** [jhuopensource/semesterly#944]
## Description

Our production site is quite slow when it comes to searching and adding/removing courses.

Running a test on the development database (which is pretty close to the production database) revealed the following result:
![image](https://user-images.githubusercontent.com/27985363/217948399-dd7d075f-4556-489d-9f6e-6d6b1e10383a.png)
121 SQL queries taking 2.4 seconds, which is pretty unacceptable, especially when it's just a single search.

## Tasks

- [ ] Identify points of inefficiency in our backend
  - [x] Course Search
  - [ ] Opening CourseModal when clicking on SearchResult
  - [ ] Adding and removing to timetable
- [ ] Optimize those points and make the appropriate changes in the frontend

## Things to consider
* Adding a db_index for commonly searched fields
* Dropping courses that are no longer relevant
* Removing schools other than JHU
* Only fetching data that we need to
