### ISSUE TITLE
Improve search engine capability to find results for queries like "oose", "ifp", etc.

### ISSUE THREAD

**Issue by JJamesWWang** [jhuopensource/semesterly#962]
# Search Engine Improvements

## Description

Semester.ly features a rather basic search engine in which the query is matched against course codes and course names based on a %LIKE% (substring) match. This means that searching for courses using their commonly abbreviated names does not work, i.e. I cannot search for "OOSE" and find "Object-Oriented Software Engineering." This is a feature that would benefit several students as search is one of the most common features that are used (citation needed).

The main issue for this project is figuring out how to make it so that when students search for "OOSE", the search engine learns to recommend "Object-Oriented Software Engineering." While it is simple to simply map abbreviations to classes, there is room to implement a more general approach that does not require hardcoding abbreviations.

## Potential Solution

While we could try an ML or NLP approach to this problem, the issue there would be lack of data. Furthermore, it may be simpler to use the Admin app to maintain a mapping from abbreviations to course names. This would be simple to implement and also take less time. We would start by conducting surveys of Hopkins students on what kind of abbreviations they use for their classes. We then set up the Admin app for a new model that's specifically used for search acronyms/initialisms (we can ignore shortened words because substring will find it). We can also set up analytics for tracking searches that fail in order to see if there's any acronyms/initialisms that we missed.

We will be going through with the Admin app approach unless we discover that it is not feasible or there exists a more beneficial solution.

## Tasks

* [ ] Research how other companies implement their search engines
* [ ] Try to figure out a way for our search engine to find the right courses given abbreviated course names.
* [ ] Create survey for Hopkins students and ask about what abbreviations they use
* [ ] Send out survey to all JHU students. We will want to try to span all majors to cover all possible course abbreviations.
* [ ] Implement changes to our basic search that allows it to return results for abbreviated course names.
  * [ ] Create SearchAbbreviation model in `searches/`
    * [ ] Determine what fields we want - we'll definitely need a field for the abbreviation and the actual course name, as well as probably index on the abbreviation.
  * [ ] Connect searches app to Admin app
  * [ ] When searching, see if there is a matching abbreviation with the query by looking up in the SearchAbbreviation table; if there is, do an OR with the original search query where it does a search by the mapped course name.
* [ ] Add an API test case that verifies basic search will display results for abbreviated course names.

## Nice To Have
* [ ] Implement optimizations to advanced search as well
* [ ] Add analytics for failed searches (?) [Needs more discussion]

## Notes

* The code that handles searching can be found in `searches/views.py`; the `get()` method is the normal search, while the `post()` method is the advanced search.
* The `SearchAbbreviation` model will probably similar to the NewsUpdate model in `notifactions/`
* The use of the admin app can also probably be modeled after the `notifications/` app, as it should be pretty similar. 
* To index a field, add the `db_index=True` argument to the constructor.
